#pragma once

#include "hemplate/classes.hpp"

namespace hemplate::html {

using hemplate::comment;
using hemplate::element;
using hemplate::transform;
using hemplate::transparent;
using hemplate::xml;

// clang-format off
using abbr       = elementBuilder<tag<"abbr">, element::Type::Boolean>;
using address    = elementBuilder<tag<"address">, element::Type::Boolean>;
using a          = elementBuilder<tag<"a">, element::Type::Boolean>;
using area       = elementBuilder<tag<"area">, element::Type::Atomic>;
using article    = elementBuilder<tag<"article">, element::Type::Boolean>;
using aside      = elementBuilder<tag<"aside">, element::Type::Boolean>;
using audio      = elementBuilder<tag<"audio">, element::Type::Boolean>;
using base       = elementBuilder<tag<"base">, element::Type::Atomic>;
using bdi        = elementBuilder<tag<"bdi">, element::Type::Boolean>;
using bdo        = elementBuilder<tag<"bdo">, element::Type::Boolean>;
using b          = elementBuilder<tag<"b">, element::Type::Boolean>;
using blockquote = elementBuilder<tag<"blockquote">, element::Type::Boolean>;
using body       = elementBuilder<tag<"body">, element::Type::Boolean>;
using br         = elementBuilder<tag<"br">, element::Type::Atomic>;
using button     = elementBuilder<tag<"button">, element::Type::Boolean>;
using canvas     = elementBuilder<tag<"canvas">, element::Type::Boolean>;
using caption    = elementBuilder<tag<"caption">, element::Type::Boolean>;
using cite       = elementBuilder<tag<"cite">, element::Type::Boolean>;
using code       = elementBuilder<tag<"code">, element::Type::Boolean>;
using col        = elementBuilder<tag<"col">, element::Type::Atomic>;
using colgroup   = elementBuilder<tag<"colgroup">, element::Type::Boolean>;
using data       = elementBuilder<tag<"data">, element::Type::Boolean>;
using datalist   = elementBuilder<tag<"datalist">, element::Type::Boolean>;
using dd         = elementBuilder<tag<"dd">, element::Type::Boolean>;
using del        = elementBuilder<tag<"del">, element::Type::Boolean>;
using details    = elementBuilder<tag<"details">, element::Type::Boolean>;
using dfn        = elementBuilder<tag<"dfn">, element::Type::Boolean>;
using dialog     = elementBuilder<tag<"dialog">, element::Type::Boolean>;
using div        = elementBuilder<tag<"div">, element::Type::Boolean>;
using dl         = elementBuilder<tag<"dl">, element::Type::Boolean>;
using doctype    = elementBuilder<tag<"!DOCTYPE html">, element::Type::Atomic>;
using dt         = elementBuilder<tag<"dt">, element::Type::Boolean>;
using embed      = elementBuilder<tag<"embed">, element::Type::Atomic>;
using em         = elementBuilder<tag<"em">, element::Type::Boolean>;
using fieldset   = elementBuilder<tag<"fieldset">, element::Type::Boolean>;
using figcaption = elementBuilder<tag<"figcaption">, element::Type::Boolean>;
using figure     = elementBuilder<tag<"figure">, element::Type::Boolean>;
using footer     = elementBuilder<tag<"footer">, element::Type::Boolean>;
using form       = elementBuilder<tag<"form">, element::Type::Boolean>;
using h1         = elementBuilder<tag<"h1">, element::Type::Boolean>;
using h2         = elementBuilder<tag<"h2">, element::Type::Boolean>;
using h3         = elementBuilder<tag<"h3">, element::Type::Boolean>;
using h4         = elementBuilder<tag<"h4">, element::Type::Boolean>;
using h5         = elementBuilder<tag<"h5">, element::Type::Boolean>;
using h6         = elementBuilder<tag<"h6">, element::Type::Boolean>;
using head       = elementBuilder<tag<"head">, element::Type::Boolean>;
using header     = elementBuilder<tag<"header">, element::Type::Boolean>;
using hgroup     = elementBuilder<tag<"hgroup">, element::Type::Boolean>;
using hr         = elementBuilder<tag<"hr">, element::Type::Atomic>;
using html       = elementBuilder<tag<"html">, element::Type::Boolean>;
using i          = elementBuilder<tag<"i">, element::Type::Boolean>;
using iframe     = elementBuilder<tag<"iframe">, element::Type::Boolean>;
using img        = elementBuilder<tag<"img">, element::Type::Atomic>;
using input      = elementBuilder<tag<"input">, element::Type::Atomic>;
using ins        = elementBuilder<tag<"ins">, element::Type::Boolean>;
using kbd        = elementBuilder<tag<"kbd">, element::Type::Boolean>;
using label      = elementBuilder<tag<"label">, element::Type::Boolean>;
using legend     = elementBuilder<tag<"legend">, element::Type::Boolean>;
using li         = elementBuilder<tag<"li">, element::Type::Boolean>;
using link       = elementBuilder<tag<"link">, element::Type::Atomic>;
using main       = elementBuilder<tag<"main">, element::Type::Boolean>;
using map        = elementBuilder<tag<"map">, element::Type::Boolean>;
using mark       = elementBuilder<tag<"mark">, element::Type::Boolean>;
using menu       = elementBuilder<tag<"menu">, element::Type::Boolean>;
using meta       = elementBuilder<tag<"meta">, element::Type::Atomic>;
using meter      = elementBuilder<tag<"meter">, element::Type::Boolean>;
using nav        = elementBuilder<tag<"nav">, element::Type::Boolean>;
using noscript   = elementBuilder<tag<"noscript">, element::Type::Boolean>;
using object     = elementBuilder<tag<"object">, element::Type::Boolean>;
using ol         = elementBuilder<tag<"ol">, element::Type::Boolean>;
using optgroup   = elementBuilder<tag<"optgroup">, element::Type::Boolean>;
using option     = elementBuilder<tag<"option">, element::Type::Boolean>;
using output     = elementBuilder<tag<"output">, element::Type::Boolean>;
using p          = elementBuilder<tag<"p">, element::Type::Boolean>;
using param      = elementBuilder<tag<"param">, element::Type::Atomic>;
using picture    = elementBuilder<tag<"picture">, element::Type::Boolean>;
using pre        = elementBuilder<tag<"pre">, element::Type::Boolean>;
using progress   = elementBuilder<tag<"progress">, element::Type::Boolean>;
using q          = elementBuilder<tag<"q">, element::Type::Boolean>;
using rp         = elementBuilder<tag<"rp">, element::Type::Boolean>;
using rt         = elementBuilder<tag<"rt">, element::Type::Boolean>;
using ruby       = elementBuilder<tag<"ruby">, element::Type::Boolean>;
using s          = elementBuilder<tag<"s">, element::Type::Boolean>;
using samp       = elementBuilder<tag<"samp">, element::Type::Boolean>;
using script     = elementBuilder<tag<"script">, element::Type::Boolean>;
using search     = elementBuilder<tag<"search">, element::Type::Boolean>;
using section    = elementBuilder<tag<"section">, element::Type::Boolean>;
using select     = elementBuilder<tag<"select">, element::Type::Boolean>;
using small      = elementBuilder<tag<"small">, element::Type::Boolean>;
using source     = elementBuilder<tag<"source">, element::Type::Atomic>;
using span       = elementBuilder<tag<"span">, element::Type::Boolean>;
using strong     = elementBuilder<tag<"strong">, element::Type::Boolean>;
using style      = elementBuilder<tag<"style">, element::Type::Boolean>;
using sub        = elementBuilder<tag<"sub">, element::Type::Boolean>;
using summary    = elementBuilder<tag<"summary">, element::Type::Boolean>;
using sup        = elementBuilder<tag<"sup">, element::Type::Boolean>;
using svg        = elementBuilder<tag<"svg">, element::Type::Boolean>;
using table      = elementBuilder<tag<"table">, element::Type::Boolean>;
using tbody      = elementBuilder<tag<"tbody">, element::Type::Boolean>;
using td         = elementBuilder<tag<"td">, element::Type::Boolean>;
using textarea   = elementBuilder<tag<"textarea">, element::Type::Boolean>;
using text       = elementBuilder<tag<"">, element::Type::Boolean>;
using tfoot      = elementBuilder<tag<"tfoot">, element::Type::Boolean>;
using th         = elementBuilder<tag<"th">, element::Type::Boolean>;
using thead      = elementBuilder<tag<"thead">, element::Type::Boolean>;
using time       = elementBuilder<tag<"time">, element::Type::Boolean>;
using title      = elementBuilder<tag<"title">, element::Type::Boolean>;
using tr         = elementBuilder<tag<"tr">, element::Type::Boolean>;
using track      = elementBuilder<tag<"track">, element::Type::Atomic>;
using u          = elementBuilder<tag<"u">, element::Type::Boolean>;
using ul         = elementBuilder<tag<"ul">, element::Type::Boolean>;
using var        = elementBuilder<tag<"var">, element::Type::Boolean>;
using video      = elementBuilder<tag<"video">, element::Type::Boolean>;
using wbr        = elementBuilder<tag<"wbr">, element::Type::Atomic>;
// clang-format on

}  // namespace hemplate::html
